In [688]:
import numpy as np
import os
from sklearn.model_selection import train_test_split
import torch 

In [689]:
with open('../../sf_vs_nyc_house_data.csv', 'r') as f:
    labels = f.readline()

print(labels)

full_data = np.genfromtxt('../../sf_vs_nyc_house_data.csv', delimiter=',')[1:]
full_data.shape

in_sf,beds,bath,price,year_built,sqft,price_per_sqft,elevation



(492, 8)

In [690]:
X_train, X_test, y_train, y_test = train_test_split(full_data[:,1:], full_data[:,:1], test_size=.2)

print(f' Train shape X: {X_train.shape} y: {y_test.shape} \n  Test shape X: {X_test.shape}  y: {y_test.shape} ')

 Train shape X: (393, 7) y: (99, 1) 
  Test shape X: (99, 7)  y: (99, 1) 


---
NOW THAT WE HAVE THAT WE CAN START TO MAKE THE NN


In [692]:
class NN():

    def __init__(self, input_size, hidden_sizes, out_size) -> None:
        self.l1 = np.random.rand(input_size,hidden_sizes[0])
        self.b1 = np.zeros((1,hidden_sizes[0]))
        self.l2 = np.random.rand(hidden_sizes[0],out_size)
        self.b2 = np.zeros((1,out_size))

    def activation_func(self, o, type):
        if type.lower()== 'relu':
            return np.where(o >= 0, o, 0)
        if type.lower() == 'softmax':
            #make val stable
            o_stable = o - np.max(o, axis=1, keepdims=True)
            o_exp = np.exp(o_stable) #e^x for each x in 0_stable
            return o_exp / np.sum(o_exp, axis=1, keepdims=True)
        if type.lower() == 'sigmoid':
            return 1/(1+np.exp(-o))
        
    def forward(self, X):
        self.X = X
        self.o1 = X @ self.l1 + self.b1
        self.h1 = self.activation_func(self.o1, 'relu')
        self.o2 = self.h1 @ self.l2 + self.b2
        self.y_hat = self.activation_func(self.o2, 'sigmoid')
        return self.y_hat
    
    def calc_loss(self, y_true, y_hat, type):
        if type.lower() == 'mse':
            return np.sum((y_true - y_hat) ** 2) / len(y_true)

    def grad_relu(self, idx=None):
        if idx is None:
            return (self.h1 > 0).astype(float) #the as type flaot turn the bool mask in 0 or 1 which is what we wnat for the relu derivative
        else:
            return (self.h1[idx] > 0).astype(float)

    def grad_mse(self, y_true): #return vextor (training_samps x 1)
        return 2 * (self.y_hat - y_true) / len(y_true)
    
    def grad_sigmoid(self): #return vextor (training_samps x 1)
        return self.y_hat * (1 - self.y_hat)

    def dl_wrt_q0(self, y_true): #return vextor (training_samps x size of layer 2)
        #print(f'this is grad wrt_q0 doe the sconf layetr: {(self.grad_mse(y_true) * self.grad_sigmoid() * self.o1).shape}')
        return self.grad_mse(y_true) * self.grad_sigmoid() * self.o1

    def dl_wrt_b2(self, y_true):
        return self.grad_mse(y_true) * self.grad_sigmoid()

    def dl_wrt_b1(self, y_true):
        return np.sum(self.grad_mse(y_true), axis=0) * np.sum(self.grad_sigmoid(), axis=0) * self.l2 * np.sum((self.grad_relu()), axis=0).reshape(self.l2.shape)

    def grad_wrt_w(self, y_true):
        #(1 x training_samps) is the dl_wrt_b1(y_true).T then we multiply accordily by the X whis is (training_samps, 7) to ge full chainrule
        #if we did dl_wrt_b1(y_true).T * one specific row we would get the gradiet for each weight in layer one for one training exmple 
        #so the do for all and them summ across the colomns or jut the dpr product
        dl_wrt_wi = self.grad_mse(y_true) * self.grad_sigmoid() * self.l2.T * self.grad_relu()
        return np.dot(dl_wrt_wi.T, self.X)

    def backprop(self, alpha, y_true, print_grads=False):
        if print_grads:
            print(f'l1 before this : {self.l1},new gradit l1: {self.grad_wrt_w(y_true)}')
            print(f'l2 before this : {self.l2},new gradit l2: {alpha * self.dl_wrt_q0(y_true)}')
            print(f'b1 before this : {self.b1},new gradit l1: {alpha * self.dl_wrt_b1(y_true)}')
            print(f'b2 before this : {self.b2},new gradit l1: {alpha * self.dl_wrt_b2(y_true)}\n\n')

        self.b2 -= alpha * np.sum(self.dl_wrt_b2(y_true), axis=0)
        self.l2 -= alpha * np.sum(self.dl_wrt_q0(y_true),axis=0).reshape(self.l2.shape)
        self.b1 = self.b1 - (alpha * self.dl_wrt_b1(y_true)).T
        self.l1 -= alpha * self.grad_wrt_w(y_true).reshape(self.l1.shape)




In [693]:
input_size = 7
hidden_sizes = [3]
out_size = 1

custom_nn = NN(input_size, hidden_sizes, out_size)

class NN_torch(torch.nn.Module):
    def __init__(self, input_size, hidden_sizes, out_size):
        super(NN_torch, self).__init__()
        self.l1 = torch.nn.Linear(input_size, hidden_sizes[0])
        self.l2 = torch.nn.Linear(hidden_sizes[0], out_size)
        self.relu = torch.nn.ReLU()
        self.sigmoid = torch.nn.Sigmoid()
    
    def forward(self, X):
        o1 = self.l1(X)
        h1 = self.relu(o1)
        o2 = self.l2(h1)
        y_hat = self.sigmoid(o2)
        return y_hat

In [694]:
#jsut setting the weights in the tourch model to be the same as the custom model

model = NN_torch(input_size, hidden_sizes, out_size)
with torch.no_grad():
    model.l1.weight = torch.nn.Parameter(torch.tensor(custom_nn.l1.T, dtype=torch.float32))
    model.l1.bias = torch.nn.Parameter(torch.tensor(custom_nn.b1.flatten(), dtype=torch.float32))
    model.l2.weight = torch.nn.Parameter(torch.tensor(custom_nn.l2.T, dtype=torch.float32))
    model.l2.bias = torch.nn.Parameter(torch.tensor(custom_nn.b2.flatten(), dtype=torch.float32))

# Verify the parameters are set correctly
print("l1 :\n", custom_nn.l1)
print("torch l1:\n", model.l1.weight.data.numpy().T)

print("b1 :\n", custom_nn.b1)
print("torch b1:\n", model.l1.bias.data.numpy())

print("l2 :\n", custom_nn.l2)
print("torch l2 :\n", model.l2.weight.data.numpy().T)

In [696]:
y_hat_torch = model.forward(torch.Tensor(X_train))

y_hat_custom = custom_nn.forward(X_train)

In [698]:
alpha = 0.001

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=alpha)

In [699]:
custom_nn.backprop(alpha, np.array(y_train)) #custom backprop

loss = criterion(y_hat_torch, torch.Tensor([y_train])) #torch backprop

#backprop and update weights
optimizer.zero_grad()

loss.backward()
print("\n\n Gradients for troucbh nn:")
for name, param in model.named_parameters():
    if param.grad is not None:
        print(f"{name} grad:\n{param.grad}")
optimizer.step()

# print the new custom params
print("\nl1 :",custom_nn.l1)
print("b1 :", custom_nn.b1)
print("l2 :", custom_nn.l2)
print("b2 :", custom_nn.b2)


#see if torch new params matches with the custom new params
print('\n\n',"Updated parameters:")
for name, param in model.named_parameters():
    print(name, param.data)

(393, 1) 
(393, 1)
(3, 1)
(393, 3)


 Gradients for troucbh nn:
l1.weight grad:
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])
l1.bias grad:
tensor([0., 0., 0.])
l2.weight grad:
tensor([[0., 0., 0.]])
l2.bias grad:
tensor([0.])

l1 : [[0.63494395 0.00445932 0.19554465]
 [0.9073893  0.41103075 0.61074752]
 [0.81401209 0.27966931 0.48087986]
 [0.84364883 0.78970556 0.86067185]
 [0.16796443 0.50251376 0.95858351]
 [0.31962584 0.03270336 0.31038375]
 [0.06840694 0.18415315 0.4375599 ]]
b1 : [[0. 0. 0.]]
l2 : [[0.96387474]
 [0.09893308]
 [0.33752933]]
b2 : [[0.]]


 Updated parameters:
l1.weight tensor([[0.6349, 0.9074, 0.8140, 0.8436, 0.1680, 0.3196, 0.0684],
        [0.0045, 0.4110, 0.2797, 0.7897, 0.5025, 0.0327, 0.1842],
        [0.1955, 0.6107, 0.4809, 0.8607, 0.9586, 0.3104, 0.4376]])
l1.bias tensor([0., 0., 0.])
l2.weight tensor([[0.9639, 0.0989, 0.3375]])
l2.bias tensor([0.])
